### ISSUE TITLE
is this the fix for patch

### ISSUE THREAD

**Issue by kurama129** [SNSA/agario-client2#1]

**Comment by kurama129** [comment]
and update your readme.md

**Comment by heroandtn3** [comment]
hello, I'm not fixing anything, I write this client from scratch.

**Comment by kurama129** [comment]
can i talk to you on skype

**Comment by heroandtn3** [comment]
Sure, my skype is heroandtn3

**Comment by kurama129** [comment]
thx ill close the issue
