### ISSUE TITLE
Can I get getInitData() without promise

### ISSUE THREAD

**Issue by wishstorage** [SNSA/agario-client2#12]
I dont know why I get always undefined values from this function

var data=core.getInitData();
console.log(data[0]); //undefined
console.log(data[1]); //undefined

**Comment by wishstorage** [comment]
May be because I try connect with opt.agent property?

connect(server) {
    logger.debug('Connecting to ' + server);
    let options = {
      headers: this.headers,
      agent: this.agent
    };

    this.ws = new WebSocket(server, null, options);
    this.ws.binnaryType = 'arraybuffer';
    this.ws.onopen     = this._onOpen.bind(this);
    this.ws.onmessage  = this._onMessage.bind(this);
    this.ws.onclose    = this._onClose.bind(this);
    this.ws.onerror    = this._onError.bind(this);

    this.authenticated = false;
  }
But mock.js returns WebSocket without agent ?

**Comment by wishstorage** [comment]
What does mock.js return?

**Comment by kurama129** [comment]
We are making progress

**Comment by heroandtn3** [comment]
> Can I get getInitData() without promise

No, the function is async, you always need promise.

> What does mock.js return?

Do not care about mock.js and core.js because they are only needed for authentication. Now we are focus on decoding packet

**Comment by wishstorage** [comment]
Ok, but in function 

WebSocket.prototype.send = function(data) {
    if ([16].indexOf(data[0]) > -1 ) return;
    console.log(data);
    let code = data[0];
    console.log(code);
    let promise = promises[code];

    if (promise) {
        promise.resolve(data.slice(0));
        delete promises[code];
    }
};
I get only one packet { '0': -2, '1': 6, '2': 0, '3': 0, '4': 0 }

what can be wrong?

**Comment by wishstorage** [comment]
@heroandtn3 what can be wrong?

**Comment by heroandtn3** [comment]
hi, sorry I do not know, it should send 2 packet with opcode -2 and -1 as usual

**Comment by wishstorage** [comment]
I have old version of node.js
