### ISSUE TITLE
Figure out how to connect to the same FFA/Party room

### ISSUE THREAD

**Issue by heroandtn3** [SNSA/agario-client2#8]

**Comment by wishstorage** [comment]
The same FFA|Party room is depend only on ip and port

**Comment by heroandtn3** [comment]
Yes, just tested with FFA room and you are right. Going to test with party room

**Comment by terjanq** [comment]
Yeah, actual system is token free, you can connect every server you want.

**Comment by hassanila97** [comment]
Nice :D  Fuck MONEYSHIT   but they will fix this as soon as the bots get public :(

**Comment by heroandtn3** [comment]
I confirm that same ip:port === same room.
